---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  namespace: gitlab-managed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: application
        image: $DOCKERHUB_USER/flask-with-test:$IMAGE_VERSION
        ports:
          - name: app-port
            containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
  name: application-lb
  namespace: gitlab-managed
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30085
  selector:
    application: app
